### Health check

GET http://localhost:8082/actuator/health

###

### Get all sectors (ADMIN only)
###@token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzZWN0b3IiOiJCYW5raW5nIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NzAwMjM0ODQsImV4cCI6MTc3MDEwOTg4NH0.XIXvR_T7IgR-_B8dbXbj1Y2zmOIhOvQZ9fFUT6ONxz8
GET http://localhost:8082/api/sectors
Authorization: Bearer {{token}}
###
#@token =eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQkFOS0lORyIsInNlY3RvciI6IkJhbmtpbmciLCJzdWIiOiJiYW5rX3VzZXIiLCJpYXQiOjE3NzE1NzY4ODYsImV4cCI6MTc3MTY2MzI4Nn0.DNl7hupgVX4jwseutPKdSWgOI2DL8_8sfl9xLKs6afg
GET http://localhost:8082/api/v1/sectors/banking/accounts
Authorization: Bearer {{token}}
###
GET http://localhost:8082/api/sectors/healthcare/patients
Authorization: Bearer {{token}}

### Login as admin
POST http://localhost:8082/api/auth/login
Content-Type: application/json


{
  "username": "admin",
  "password": "admin123"
}


###
POST http://localhost:8082/api/auth/login
Content-Type: application/json

{
  "username": "bank_user",
  "password": "bank123"
}
###
POST http://localhost:8082/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}


###
POST http://localhost:8082/api/auth/register
Content-Type: application/json

{
  "username": "51user",
  "password": "password123",
  "email": "test15@test.com",
  "sectorId": 2,
  "role": "USER"
}

###
GET http://localhost:8082/api/v1/sectors/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzZWN0b3IiOiJCYW5raW5nIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NzIzNzIyODksImV4cCI6MTc3MjQ1ODY4OX0.RJ-Wny8abOOTKtbO8W6CiBXxmKti8kcQZV7sFd656T4
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}