package com.example.cms.event;

public enum SectorEventType {

    CREATED,
    UPDATED,
    DELETED,

    ACCOUNT_CREATED,
    TRANSACTION_PROCESSED,
    BALANCE_UPDATED,
    LOAN_APPROVED,

    PATIENT_REGISTERED,
    APPOINTMENT_SCHEDULED,
    PRESCRIPTION_ISSUED,
    LAB_RESULT_READY,

    STUDENT_ENROLLED,
    COURSE_COMPLETED,
    GRADE_SUBMITTED,

    ORDER_PLACED,
    PAYMENT_PROCESSED,
    INVENTORY_UPDATED,
    SHIPMENT_DISPATCHED,

    PRODUCTION_STARTED,
    QUALITY_CHECK_COMPLETED,
    INVENTORY_RESTOCKED,
    ORDER_FULFILLED
}
