apiVersion: v1
kind: Namespace
metadata:
  name: cms-production
  labels:
    name: cms-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: cms-staging
  labels:
    name: cms-staging
    environment: staging
