spring.application.name=CMS

# ===============================
# SERVER
# ===============================
server.port=8082

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/cms_db
spring.datasource.username=postgres
spring.datasource.password=Hello@123!

# ===============================
# JPA / HIBERNATE
# ===============================
# VERY IMPORTANT FOR NOW
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# KAFKA (DISABLED FOR NOW)
# ===============================
spring.kafka.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=mySuperSecretJwtKeyThatIsAtLeast64CharactersLongForHS256Algorithm
jwt.expiration=86400000

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.cache.type=simple