spring.application.name=CMS

# ===============================
# SERVER
# ===============================
server.port=8082

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/cms_db
spring.datasource.username=postgres
spring.datasource.password=Hello@123!

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# KAFKA (DISABLED)
# ===============================

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=mySuperSecretJwtKeyThatIsAtLeast64CharactersLongForHS256Algorithm
jwt.expiration=86400000

# ===============================
# ENCRYPTION
# ===============================
encryption.key=0uip6i0HH6xmSJR3oR8sZ+hK5PdrxnQjRq8L+58nFwo=

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

# ===============================
# LOGGING (Cleaned)
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate=INFO

spring.cache.type=simple